# Importing Libraries

In [ ]:
import pandas as pd
import sqlite3

### Loading Dataset

In [ ]:
df = pd.read_csv("cleaned_data.csv")

### Creating Database

In [2]:
conn = sqlite3.connect("ecommerce.db")

In [3]:
df.to_sql(
    "orders",
    conn,
    if_exists="replace",
    index=False
)

1200

### Checking Database working properly

In [13]:
def run_query(query):
    return pd.read_sql_query(query, conn)

### Total Orders

In [14]:
query = """
SELECT COUNT(*) AS Total_Orders
FROM orders
"""

run_query(query)

   Total_Orders
0          1200

### Total Revenue

In [15]:
query = """
SELECT SUM(TotalPrice) AS Total_Revenue
FROM orders
"""

run_query(query)

   Total_Revenue
0     1264761.96

### Average Order Value

In [16]:
query = """
SELECT AVG(TotalPrice) AS Avg_Order_Value
FROM orders
"""

run_query(query)

   Avg_Order_Value
0        1053.9683

### Checking Higher Product Revenue

In [8]:
query = """
SELECT Product,
SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY Product
ORDER BY Revenue DESC
"""

run_query(query)

   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41
5     Desk  167459.93
6    Phone  151722.39

### Checking Total Orders by Order Status

In [18]:
query = """
SELECT OrderStatus,
COUNT(*) AS Total_Orders
FROM orders
GROUP BY OrderStatus
"""
run_query(query)

  OrderStatus  Total_Orders
0   Cancelled           250
1   Delivered           231
2     Pending           237
3    Returned           247
4     Shipped           235

### Checking Revenue by Payment Method

In [19]:
query = """
SELECT PaymentMethod,
SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY PaymentMethod
ORDER BY Revenue DESC
"""

run_query(query)

  PaymentMethod    Revenue
0   Credit Card  263847.63
1        Online  262442.94
2          Cash  259786.29
3     Gift Card  246323.92
4    Debit Card  232361.18

### Checking Refferal Source

In [11]:
query = """
SELECT ReferralSource,
COUNT(*) AS Orders
FROM orders
GROUP BY ReferralSource
ORDER BY Orders DESC
"""

run_query(query)

  ReferralSource  Orders
0      Instagram     259
1          Email     250
2         Google     241
3       Facebook     228
4       Referral     222

### Checking the orders that's price greater than 3000

In [20]:
query = """
SELECT Count(*)
FROM orders
WHERE TotalPrice > 3000
ORDER BY TotalPrice DESC
"""

run_query(query)

   Count(*)
0        34

### SQL Concepts Applied

* SELECT
* WHERE
* ORDER BY
* GROUP BY
* COUNT()
* SUM()
* AVG()

### Objectives

* Analyze revenue performance
* Evaluate product sales
* Examine customer acquisition channels
* Measure payment method usage
* Investigate order status trends

SQL queries were used to extract actionable business insights from the dataset.